### ISSUE TITLE
Map Column Heading to Multiple Possible Names

### ISSUE THREAD

**Issue by CallumVass** [hughbe/excel-mapper#15]
Hi,

I have some excel files which have a different heading but I want to map them to the same Property in my class, I have tried the following but it throws an exception:

```
Map(e => e.CourseDateTime)
                .WithColumnName("Time___Date_of_training")
                .WithColumnName("Time___Date_of_Training")
                .WithColumnName("Training_Date___Start_Time");
```

I was just wondering if I am missing a config setting when setting up my mapper or if this is even possible at the moment? Thanks

**Comment by CallumVass** [comment]
I've just had some spare time so began working on it. Would this suffice? If so I will begin writing some tests for it: https://github.com/CallumVass/excel-mapper/commit/3373474125cd3d9bf33662f4edd482799c79fa0d

**Comment by hughbe** [comment]
Yes! I like this addition.

Couple of comments:
- change the overload to be `params string[]`
- add an `IEnumerable<string>` overload

I’m not sure about the `WithPossibleColumnNames` name. Maybe something like `WithFirstOfColumnNames`  Up to you thoigj

**Comment by hughbe** [comment]
actually. Maybe we should change this to (or add an alternate API) something that is more versatile?

Maybe like
`WithColumnNameMatching(Action<string, book> predicate)`

This could be interesting but I do think first we should add the API you shggested

**Comment by CallumVass** [comment]
Actually you're right I quite like the Matching API. I will change my code to that and try get it done tonight. Thanks.

**Comment by CallumVass** [comment]
Hi,

How does this look? If you're happy I will add some tests

https://github.com/CallumVass/excel-mapper/commit/97d6ff6996f7af236f2557065cf3a5cb6e77c8b4

**Comment by CallumVass** [comment]
I've added some tests now. I've also added .net 2.1 as a targeting framework for the test project. If that's not okay let me know and I'll remove it. Thanks

**Comment by hughbe** [comment]
Fixed 🎉

**Comment by hughbe** [comment]
Fixed 🎉
