### ISSUE TITLE
Case insensitive enum mapper

### ISSUE THREAD

**Issue by bobinush** [hughbe/excel-mapper#19]
https://github.com/hughbe/excel-mapper/blob/5b903cf9776139d5379b7848bff307726173f624/src/Mappings/Mappers/EnumMapper.cs#L39
Add a property to ignore case?
https://msdn.microsoft.com/en-us/library/kxydatf9(v=vs.110).aspx

Like [you said](https://github.com/hughbe/excel-mapper/pull/18#issuecomment-409512761) with the case sensitive header, maybe introduce a property on ExcelSheet for this too?

**Comment by hughbe** [comment]
I like this idea it makes sense and is versatile. I don't think this belongs on `ExcelSheet` but is really something the user should configure in a class map.

The basic idea is that in your class map you do something like
```
public class CustomMap : ExcelClassMap<YourClass>
{
    public CustomMap()
    {
        Map(value => value.EnumValue, ignoreCase: true);
    }
}
```

I've added an overload to a class map and the following example should help:
```cs
public enum MaritalStatus
{
    Married,
    Single,
    Invalid,
    Unknown
}

public class President
{
    public string Name { get; set; }
    public MaritalStatus MarritalStatus { get; set; }
}

public class PresidentClassMap : ExcelClassMap<President>
{
    public PresidentClassMap()
    {
        Map(president => president.Name);

        Map(president => president.MarritalStatus, ignoreCase: true)
            .WithColumnName("Marrital Status")
            .WithEmptyFallback(MaritalStatus.Unknown)
            .WithInvalidFallback(MaritalStatus.Invalid);
    }
}
```
