### ISSUE TITLE
Make ExcelSheet.CurrentIndex public

### ISSUE THREAD

**Issue by BalassaMarton** [hughbe/excel-mapper#20]
Currently, if any of the property mappers throw an exception during `ReadRows`, there is no way to get the index of the problematic row. Making `CurrentIndex` a read-only public property would solve this problem.

**Comment by hughbe** [comment]
Sure! Do you want to make a PR

**Comment by BalassaMarton** [comment]
If you accept PRs then yes, I'll do it on the weekend.

**Comment by hughbe** [comment]
Exposed as
```cs
public class ExcelSheet
{
        /// <summary>
        /// Gets the index of the row currently being mapped.
        /// </summary>
        public int CurrentRowIndex { get; }
}
```
