### ISSUE TITLE
Make `ExcelClassMap.Mappings` public

### ISSUE THREAD

**Issue by BalassaMarton** [hughbe/excel-mapper#22]
Another point of extensibility that I desperately need: to modify the class map from outside. This would allow us to add custom generic extension methods, like make every column optional (which is currently impossible) or automatically add mappers based on property type, etc.
In fact, all currently internal mapping methods should be public and have a non-generic version, but that at least can be circumvented by dynamically invoking the generic versions.
I know I said 'I will do it over the weekend' in another post and never delivered, but if you say you'll merge the PR, I'll do it for real this time as I can't create a workaround for this.

**Comment by hughbe** [comment]
Hey this is interesting but could you clarify which classes you want to be made public?

**Comment by BalassaMarton** [comment]
I'll probably submit a PR, but making the `ExcelClassMap.Mappings` property public would add a lot of value.

**Comment by hughbe** [comment]
Oh! You mean the property rather than the namespace, my bad!! I can do this myself don't worry I will send in a PR then push to nuget within the next hour

**Comment by hughbe** [comment]
Now exposed as
```
public class ExcelClassMap
{
    public ExcelPropertyMapCollection Mappings { get; set; }
};
```

**Comment by BalassaMarton** [comment]
Great!
