### ISSUE TITLE
Add VisibleState property to ExcelSheet

### ISSUE THREAD

**Issue by BalassaMarton** [hughbe/excel-mapper#28]
Please add a property to `ExcelSheet` that can be used to read the visibility of the sheet, preferably as an `enum` instead of text:

```cs
public enum ExcelSheetVisibility {
    Visible,
    Hidden,
    VeryHidden
}
```
Some input files can have hidden sheets and it's hard to automate things like reading data from every visible sheet (my current workaround being opening the file with `ExcelDataReader` first, and iterating through the sheets to find out which one is visible).

**Comment by hughbe** [comment]
Right - can you clarify what VeryHidden means and how I would get these values?

**Comment by BalassaMarton** [comment]
`IExcelDataReader.VisibleState`. `VeryHidden` means the user can't switch it to visible, only the VBA code. I'd say if you just add it as `string` and set the value when reading the sheet, we're one step closer, but a `string` property is so lame when the possible values are fixed.

**Comment by hughbe** [comment]
Fixes in https://www.nuget.org/packages/ExcelDataReader.Mapping/1.1.2
