### ISSUE TITLE
How to read arbitrary types with custom cell mappers

### ISSUE THREAD

**Issue by BalassaMarton** [hughbe/excel-mapper#38]
I'm trying to read a dictionary property using a custom `ICellValueMapper` (basically the data would be stored as a JSON string). How can I map this property? Calling `ExcelClassMap<T>.Map` throws an exception (Don't know how to map type System.Collections.Generic.IDictionary...). Which is frustrating since the whole point of custom cell value mappers would be to allow mapping arbitrary values to arbitrary types. Is there a way I can map a property type that is not supported out of the box?

**Comment by hughbe** [comment]
Yeah I'm working on this in #25
