### ISSUE TITLE
Mapping to nullable decimal with InvalidFallback results in value 0 instead of null

### ISSUE THREAD

**Issue by maaroen** [hughbe/excel-mapper#42]
The following code results in the value 0 in the column AmountPerLayer, but I expected the value null.

Am I doing something wrong?

`Map(fust => fust.AmountPerLayer)
			.WithColumnIndex(3)
			.WithInvalidFallback((decimal?)null)
			.WithEmptyFallback((decimal?)null);`

**Comment by hughbe** [comment]
what was the value of cell in column index 3?

**Comment by maaroen** [comment]
> what was the value of cell in column index 3?

Most cells have a value like 1 2 5 6 6 4 3 
And these are working well, but there are a few containing text or that are empty. These result in a 0 value, but I expected a null.

**Comment by hughbe** [comment]
Is `AmountPerLayer` defined as a `decimal?` i.e. nullable decimal? Could you share your structure

**Comment by hughbe** [comment]
If the type is nullable decimal, maybe could you share the excel file?

**Comment by maaroen** [comment]
Yea it is a nullable decimal, let me see if I can get a part out of the file without sharing sensitive data.
column is like this
Empty
Some Text
Some Text
Empty
Empty
5
3
6

**Comment by maaroen** [comment]
I just found out that the "empty" fields had a hidden value of 0, that's why it didn't work.
So it does work as intended, sorry for the confusion!
