### ISSUE TITLE
Set the header row

### ISSUE THREAD

**Issue by mvmcjr** [hughbe/excel-mapper#5]
Sometimes the header is not on the first row, please let us be able to set it.

**Comment by hughbe** [comment]
Makes sense.

Were you thinking of something like 
```
public class ExcelSheet
{
...
    public int HeaderIndex { get; set; } = 0;
...
}
```

**Comment by redbaty** [comment]
@hughbe Yes, I tried developing it but got sorta stuck somewhere I can't remember

**Comment by hughbe** [comment]
@redbaty can you clarify what you would expect to happen for rows before the header index? Would they simply be skipped and then we read down from there?

**Comment by redbaty** [comment]
@hughbe Well, in my opinion they should be skipped, cause usually they don't refer to the table you want to read

**Comment by hughbe** [comment]
Great! I just pushed an addition for this feature. You'll need to update the nuget package once I publish it. It'll be up in a couple of hours.

Take a look at the readme for usage details: https://github.com/hughbe/excel-mapper#mapping-sheets-where-the-header-is-not-the-first-row

**Comment by redbaty** [comment]
Great, thanks!
