### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by jumpingjackson** [hughbe/excel-mapper#58]
1. I found IFallBackItem and .WithInvalidFallbackItem() , is there a way to see why it failed to map or some kind of error message?  I would like to be able to collect all the cell level errors (dont stop on the first error found) from the file and later display them to a user. ( I can handle the display part i just need a callback of some sort to enable me to collect them)

2. I would also like to be able to throw custom errors during the mapping conversion inside something like .WithConverter(value => int.Parse(value) / 100f) if certain conditions are met.   Is this possible?  Ideally would like to be able to see the error message in 1.

Thank you!  this project looks really useful

Edit:   
Looking at the source code i was considering adding an ErrorMessage property to ReadCellValueResult, and then setting it where applicable in the existing ICellValueMapper 's and then implementing my own ICellValueMappers where needed. :)

**Comment by jumpingjackson** [comment]
I found IFallBackItem and .WithInvalidFallbackItem()  , is there a way to see why it failed to map or some kind of error message?

**Comment by hughbe** [comment]
I like the idea of this but I'm slightly struggling to find a way to implement this without breaking the public API

> I found IFallBackItem and .WithInvalidFallbackItem() , is there a way to see why it failed to map or some kind of error message? I would like to be able to collect all the cell level errors (dont stop on the first error found) from the file and later display them to a user. ( I can handle the display part i just need a callback of some sort to enable me to collect them)

I need to take a deeper look at this and think about the API shape

> I would also like to be able to throw custom errors during the mapping conversion inside something like .WithConverter(value => int.Parse(value) / 100f) if certain conditions are met. Is this possible? Ideally would like to be able to see the error message in 1.

Currently we catch all the errors in `WithConverter`. One option you could do for now is to do
```
public class ClassMap : ExcelClassMap<MyClass>
{
    public List<Exception> Exceptions { get; } = new List<Exception>();

    public ClassMap()
    {
        Map(c => c.Value)
            .WithConverter(value =>
            {
                try
                {
                    return int.Parse(value) / 100f;
                }
                catch (Exception ex)
                {
                    Exceptions.Add(ex);
                }
            });
    }
}
```

That way you can get a list of exceptions from
```cs
using var importer = ...; // create importer
var map = new ClassMap();
importer.Configuration.RegisterClassMap(map);

ExcelSheet sheet = importer.ReadSheet();
var rows = importer.ReadRows();

// Get the list of errors:
foreach (Exception ex in map.Exceptions)
{
    Console.WriteLine(ex);
}
```

**Comment by cja100** [comment]
How about an addition to the public API, a ValidateRows method could simply return a list of errors? Of course that means running through the rows twice when the spreadsheet is valid, but in most cases you don't want to do anything with any rows if some of the spreadsheet is invalid. 

This way we can return nice errors to the user that state the cell that has an issue.
