### ISSUE TITLE
ColumnIndexReader TryGetValue Shouldn't Restrict By ResultsCount

### ISSUE THREAD

**Issue by jeffolmstead** [hughbe/excel-mapper#59]
First off, GREAT solution, thanks. I am pretty sure I have found a bug and am reporting it. In "ExcelMapper.Readers.ColumnIndexValueReader" (filename is "ColumnIndexReader.cs") this is what currently exists

```
public bool TryGetValue(ExcelSheet sheet, int rowIndex, IExcelDataReader reader, out ReadCellValueResult result)
{
    if (ColumnIndex > reader.ResultsCount)
    {
        result = default;
        return false;
    }

    var value = reader[ColumnIndex]?.ToString();
    result = new ReadCellValueResult(ColumnIndex, value);
    return true;
}
```

As I understand it, "ResultsCount" is the number of worksheets in the workbook. As such, this will prevent the return of any columns beyond the number of worksheets. I believe instead it should be "FieldCount" as shown here:

```
public bool TryGetValue(ExcelSheet sheet, int rowIndex, IExcelDataReader reader, out ReadCellValueResult result)
{
    if (ColumnIndex > reader.FieldCount)
    {
        result = default;
        return false;
    }

    var value = reader[ColumnIndex]?.ToString();
    result = new ReadCellValueResult(ColumnIndex, value);
    return true;
}
```

After this change, everything works (as expected) on my end.

**Comment by hughbe** [comment]
Damn! Thats a bad bug

Will fix now

**Comment by hughbe** [comment]
Releasing version [2.1.1](https://www.nuget.org/packages/ExcelDataReader.Mapping/2.1.1)

Please let me know if anything else doesn't work or there are any missing features etc.

**Comment by hughbe** [comment]
I suppose a rudimentary fix if you're struggling with this would be to spam add a bunch of sheets to your doc haha!

**Comment by jeffolmstead** [comment]
Ha, I love that fix, that really should be the official response. No, it is not broken, add more sheets!!!

**Comment by jeffolmstead** [comment]
I have installed version 2.1.1. and reran the process which was failing. Everything ran through properly this time. Thanks for the speedy turnaround.
