### ISSUE TITLE
Maximum rows

### ISSUE THREAD

**Issue by bfallar3** [hughbe/excel-mapper#61]
When reading more than 1K rows, it failed. Is this the limitation?

**Comment by hughbe** [comment]
What error do you get? Can you share an example?

**Comment by hughbe** [comment]
Looking at the benchmark here
```
[Benchmark]
public void DefaultMap()
{
    using var original = Helpers.GetResource("VeryLargeSheet.xlsx");
    var importer = new ExcelImporter(original);
    importer.Configuration.RegisterClassMap<DataClassMap>();

    ExcelSheet sheet = importer.ReadSheet();
    foreach (object value in sheet.ReadRows<DataClass>())
    {
    }
}
```

We have 7,500 rows in the `VeryLargeSheet.xlsx` - can you please describe your error more as I cant repro

**Comment by hughbe** [comment]
Hi, any updates? I'm going to close this soon if no updates

**Comment by bfallar3** [comment]
I haven't test it yet, but u can close the issue I guess, thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hughbe** [comment]
Cheers!
