### ISSUE TITLE
Nuget Package

### ISSUE THREAD

**Issue by ltemimi** [hughbe/excel-mapper#65]
Is there a nuget package for Excel-Mapper? if so what is the name of the package?
Thanks
Laz

**Comment by hughbe** [comment]
https://www.nuget.org/packages/ExcelDataReader.Mapping/

Updated the readme

**Comment by ltemimi** [comment]
Thanks
#Another feedback I got the following error
System.TypeLoadException
  HResult=0x80131522
  Message=Could not load type 'ExcelMapper.ExcelImporter' from assembly 'ExcelMapper, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

I needed
 System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);
and it worked

**Comment by hughbe** [comment]
Thanks for that! Good to document these things :))


Let me know how you find the library - any bugs, additions, queries etc
