### ISSUE TITLE
Import file without header row

### ISSUE THREAD

**Issue by rudolph2907** [hughbe/excel-mapper#9]
Hi 

Is there a way import the file without a header and just use the column index to map your file?

Please let me know.

Thanks

**Comment by hughbe** [comment]
Set `HasHeading` to `false` on the excel sheet in question.
Then you need to define a custom class map and register it. Within the class map constructor, call `Map(x => x...).WithColumnIndex(YOUR_COLUMN_INDEX)`

**Comment by hughbe** [comment]
Keeping this issue open to add an example to the documentarion

**Comment by rudolph2907** [comment]
Hi @hughbe 

The HasHeading property is read-only:
![image](https://user-images.githubusercontent.com/4610580/34408361-0a22a7e4-ebcc-11e7-933d-50e1fb678831.png)

**Comment by hughbe** [comment]
Oh, my bad.

You’ll want to set the `HasHeading`Property on `ExcelImporterConfiguration`

**Comment by rudolph2907** [comment]
Thanks, is it possible to give me a quick example as I am not sure how to set the property with this signature: 
![image](https://user-images.githubusercontent.com/4610580/34409177-bd067a62-ebd0-11e7-9a7d-f518e882bf0a.png)

**Comment by hughbe** [comment]
Hi @rudolph2907 I've actually redone the way this works. You now can set `sheet.HasHeading = false;` for the sheet in question. You can see an example in the readme: https://github.com/hughbe/excel-mapper#mapping-sheets-without-headers

You'll need to update the nuget package to the latest version (I'm going to publish an update in an hour or so when I fix some other bugs etc.)

**Comment by rudolph2907** [comment]
Thanks @hughbe, that will be much easier.
